name: Feature Request
description: Suggest an improvement to Plex that would help users
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got a good idea? You’re in the right place.

        This tracker is organized by **fellow Plex users**, not the official team. We're trying to surface **clear, thoughtful ideas** that solve real user problems—and make it easier for Plex to take notice.

        If Plex does pick up on these ideas, it’ll be because of thoughtful input like yours. Let’s raise the bar, together.

  - type: input
    id: feature_summary
    attributes:
      label: What’s your idea in one line?
      placeholder: e.g. "Add picture-in-picture on iPad"

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: e.g. “I want to keep watching while replying to messages.”

  - type: textarea
    id: your_idea
    attributes:
      label: Describe your idea
      description: How would it work? What's the ideal behavior?

  - type: textarea
    id: tried
    attributes:
      label: Have you tried anything else?
      placeholder: e.g. “Tried backgrounding the app but playback pauses.”

  - type: dropdown
    id: feature_platforms
    attributes:
      label: Where would this feature be useful?
      multiple: true
      options:
        - Windows
        - macOS
        - iOS
        - Android
        - Apple TV
        - Roku
        - Web app
        - Server side
        - Everywhere

  - type: input
    id: mockups
    attributes:
      label: Links to mockups or examples (optional)

  - type: textarea
    id: extra_context
    attributes:
      label: Anything else to add?
